### ISSUE TITLE
Setup form for donors to be added to the donor wall

### ISSUE THREAD

**Issue by pkscout** [xbmc/kodi-tv#10]
This will likely use Netlify forms and then some kind of API call or export to get them into a format that can be parsed by a new gatsby addon (that will have to be written).

**Comment by pkscout** [comment]
Well, good news/bad news. I got the Netlify form setup, but we only get 100 form submissions a month before we have to pay. I went and looked at the current donor wall, and there were 20 submissions in the last three days. If that's a normal pace, we'll blow through our form submissions in two weeks. I think we're going to need somewhere to dump the donor wall submissions and then build a process to get the donor wall info somewhere I can get with a Gatsby addon.

**Comment by Razzeee** [comment]
google sheets 🤓

**Comment by yol** [comment]
It's not a big issue to get a place to dump it, but I'm wondering how the interaction could look like? Like if we redirect to a URL that saves the submission into a DB, how do we know it was a "real" donation?

**Comment by pkscout** [comment]
Right now what I'm hoping to find is just somewhere I can use an API or something like it to save form data I already have. The new donor setup only shows the donor wall form if it gets data back from Stripe or Paypal (by checking the referring URL, so there's a lower probability that someone "hacks" it.  I'm looking at the Google Sheets suggestion, and it might just work. There are examples of using React and a little Google scripting to save data to a sheet, and I found a Gatsby source addon that will get data from a sheet to use during build, so that would solve the problem of building the donor wall too.

**Comment by yol** [comment]
Where does the code to save the form data run? In the browser? Refer URL check is not enough, unfortunately.

The current site uses IPN for PayPal, which is the "correct" way to do it. We can host that outside of Netlify. Maybe Stripe has something similar?

**Comment by pkscout** [comment]
It looks like you might be able to use Stripe webhooks to do what Paypal IPN does.

https://stripe.com/docs/webhooks

At this point, someone else is going to need to take on the post processing. I've reached the end of what I can do. Once someone can tell me what URL the payment sites should use as a return, I'll update the form.  Then we can figure out how to get that information back out so I can use it in Gatsby to build the donor wall.

**Comment by yol** [comment]
I guess we could use our AWS credit in some form, e.g. AWS Lambda. Costs should be negligible.

**Comment by yol** [comment]
Trying to get it up&running with Lambda -> DynamoDB. Then you only need some code to get it out of dynamodb, which shouldn't be too difficult. This is the API: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB.html

**Comment by yol** [comment]
Stripe working, code here

https://github.com/xbmc/aws/

Now on to PayPal

**Comment by yol** [comment]
PayPal now also working. We need to change the IPN in the PayPal account when we switch the webpage though.

**Comment by pkscout** [comment]
This should now be complete. I'm going to close this, but we can reopen it if needed.
