### ISSUE TITLE
Reorganise media tiles in About page

### ISSUE THREAD

**Issue by KarellenX** [xbmc/kodi-tv#104]
Is it possible to move the "Games" tile in **What can Kodi do for me?** section up with the rest of the media tiles?

Not too concerned about how the last two lines are ordered so it does not need to be a direct swap of the two tiles.

![games](https://user-images.githubusercontent.com/44626605/112072810-c03de780-8bc6-11eb-808c-08f0c5171754.jpg)

**Comment by pkscout** [comment]
Done and available to preview in staging at: https://kodi-tv-staging.netlify.app/about/.  I'll leave this open until we merge the change into main.

**Comment by pkscout** [comment]
Change merged into main. If the new order still doesn't make sense, please reopen this issue.
