### ISSUE TITLE
Sponsor logos should be links to sponsor sites

### ISSUE THREAD

**Issue by pkscout** [xbmc/kodi-tv#107]
On the home page and the sponsors page, the logos for our sponsors should link to the link provided by the sponsor (i.e. the same one used in the footer).

**Comment by Razzeee** [comment]
I'm working on this

**Comment by pkscout** [comment]
I've confirmed this all works in staging (including the CMS admin). I'm going to close this.  It'll get merged into main whenever I do that again (maybe at the end of the weekend).
