### ISSUE TITLE
Jerky hero transition on main page.

### ISSUE THREAD

**Issue by KarellenX** [xbmc/kodi-tv#116]
I have noticed that when **first** arriving on the home page, the hero image slide at the top of the page has a rough transition. 

In less than 1 second, it goes from no image, first image, no image then to image again and the slideshow continues correctly after that.

You can step through the video clip ... https://streamable.com/jm7tfo

**Comment by Razzeee** [comment]
https://github.com/nolimits4web/swiper/issues/3875

**Comment by KarellenX** [comment]
fixed
