### ISSUE TITLE
Images from /sites/default/files/uploads/ path seem to be missing

### ISSUE THREAD

**Issue by Razzeee** [xbmc/kodi-tv#118]

**Comment by pkscout** [comment]
I found them, and it looks like there are some other images in a couple other paths too.  I'm converting them all to webp and updating the blog posts with the new image paths.

**Comment by pkscout** [comment]
OK, I think I'm done.  There were random files in weird places, but I tracked most of them down.  I've gone through every blog post to make sure that at least the featured image is valid (or deleted it in a few cases), so every post either has an image or shows the default color in the top of the card. I can't say for sure that every blog post has every image, but we may be as close as we're going to get.

**Comment by Razzeee** [comment]
Yeah, I've gone through the first few pages, this weekend. There seemed to be some other missing, that should be named `image.webp` but were `image_0.webp` or `image_1.webp`

**Comment by pkscout** [comment]
Everything I've done is in staging now, and I went ahead and merged it with main for a rebuild.

**Comment by Razzeee** [comment]
Has that been build or is this page expected to have no pictures? https://kodi-tv-staging.netlify.app/blog/page/30

**Comment by pkscout** [comment]
That last page is all 16+ year old blog posts from like 3 web platforms ago, and it looks like they never had a featured image in a way that was understood that way. So yes, it's probably expected for pages further to the back to have no featured image. I'm still hoping we can maybe trim back some of the old posts. Like this only letting folks know that Xboxes with 1400 Mhz processors are now available.

https://kodi-tv-staging.netlify.app/article/xboxes-1400mhz-processor-finally-sale/

'-)

**Comment by Razzeee** [comment]
Kinda neat, that we still got them

**Comment by pkscout** [comment]
I'm going to go ahead and close this. I suspect we still have some images in the body of a few blog posts that are missing, but they're likely from much older posts. When we deal with the post tagging we can probably go through and clean up the last few images too and either remove them or download them from the current site by hand.
