### ISSUE TITLE
Link styling

### ISSUE THREAD

**Issue by Razzeee** [xbmc/kodi-tv#120]
Some links seem to be blue some are black and underlined (see addons)

I think we need to find a middle ground. If we go for the bluish links, it should probably be the kodi blue? (or the blue from the current page?)

**Comment by pkscout** [comment]
Agreed.  This is a case where it might be good to have a named class/style for this so we can use the reference everywhere and update it in the style sheet if needed.  `kodi` may be a bit bright, but `kodi-darker` could be a good choice.  I don't know that I have a strong preference for underlined or not.  We might have two styles of links, as there are some places (like the main page) that underlined links look strange, but in text heavy ones I think the underline helps.  I wonder if we can just override the prose-blue class, as most of the text heavy pages are wrapped in the prose class.

**Comment by Razzeee** [comment]
I would try to start without an underline and with `kodi-darker` and `kodi` for visited links

**Comment by pkscout** [comment]
That works for me.

**Comment by pkscout** [comment]
I've tried a couple of things to define the a:link and a:hover globally, but it doesn't seem to apply consistently. I can't figure out what's overriding it (even if I delete all the text color references in the utility class calls it still doesn't seem to take the default global setting).  I finally just reverted all my local changes and gave up for now.  Maybe there's a better "tailwindy" way to do this.

**Comment by pkscout** [comment]
I added a hover style for links (kodi-lighter) and fixed the standard icon list so it respects the link coloring.  From a style guide perspective I'm going with the idea that links in blocks of text should be underlined (which prose gives us by default) but that links in buttons (I'm including IconList as a button type) should have the color but not underlined.  The header and footer are special cases, so they have their own link and button styling.

The only place I know of now that doesn't follow this guidance is the Blog Navigation Card. The links are considered buttons, but having that much kodi-darker text is a bit over powering to me.  I may take another look at that.
