### ISSUE TITLE
Kodi audio pass through option is not working properly 

### ISSUE THREAD

**Issue by cmeng-git** [xbmc/kodi-tv#127]
Running Kodi v19.0 on android box v7 (Mecool Pro III), with hdmi output connected to Denon X2700H for audio processing.

Setting kodo audio output option to pass-through to Denon X2700H for ATMOS playback using the file downloaded from: 
https://thedigitaltheater.wetransfer.com/downloads/4760c99ef450d9996eb544fbb19fab2c20190819232713/c55fb3

Found that Kodi does not always pass through the audio data stream to X2700H successfully for ATMOS audio decoding; no audio output is heard from the X2700H. Perform Setting change during media playback, set audio to pass-through, and cycle through all the available audio streams, the playback is choppy and does not sustain the data streaming properly. However when disable the audio pass through, then audio playback on X2700H has no problem.

**Comment by pkscout** [comment]
This is the repo for the Kodi web site. For assistance using Kodi you should really use our Forums at:

https://forum.kodi.tv

There is an area there specifically for Android.

https://forum.kodi.tv/forumdisplay.php?fid=164
