### ISSUE TITLE
Remove references to XBMC

### ISSUE THREAD

**Issue by pkscout** [xbmc/kodi-tv#14]
It appears to be time to retire the "formerly XBMC" phrasing. I think the only place that comes up is in the grey footer bar, so that's a template change. If we find others, we should obviously fix those too.

**Comment by pkscout** [comment]
OK, here's a question. Is the foundation still called the XBMC Foundation, or was there a name change there too.  I did find a bunch of references to the XBMC Foundation and need to know if they should be changed.

**Comment by Razzeee** [comment]
We do "own" both XBMC Foundation and Kodi Foundation

**Comment by pkscout** [comment]
Done with bf0ea913af8101b2f619856785cc21441551fce8 and fb7c8a3d0178242ba6de6b41d33576b11cdff568.

**Comment by pkscout** [comment]
Having heard nothing, I'm declaring this done. If anything got missed, we can open a new ticket for the specific issue.
