### ISSUE TITLE
Pre-Production: Check if URLs match

### ISSUE THREAD

**Issue by Razzeee** [xbmc/kodi-tv#140]
One of the last checks before we move this to production should be an additional check, if the old URLs are still going to match.

**Comment by pkscout** [comment]
For the blog at least the URLs should be the same. I kept the same weird structure where we call it news, have the index at `/blog` and each item is at `/article/<name>`. Kind of a pain to setup, but it was probably worth it to keep those URLs intact. The likelihood is that none if the add-on section is the same. The rest of it (which is a small piece), my bet is about 80% is the same. Netlify does have a redirect plugin, so we could use that for critical files and then perhaps put something in the 404 explaining the site change and pointing folks to some places we know changed.

**Comment by Razzeee** [comment]
I think news and the main pages will be the most important stuff. Addons would be nice, but I think we can live with that.

**Comment by pkscout** [comment]
I went through the old site and made sure that all the menu items and footer links had redirects if they weren't the same. I also added a little info to the 404 page for some things we know have changed (like blog tag links and add-on links).  Tested all the redirects, and they work fine. The 404 page will get updated with the auto update around 2am UTC.
