### ISSUE TITLE
Discussion: Settle on Tags for Blog Posts

### ISSUE THREAD

**Issue by pkscout** [xbmc/kodi-tv#143]
Now that we have a pretty well set UI for the web site, I'd like to see about settling on some tags for blog posts.  I've gone through all 43 of the tags on the current site.  A chunk of them have no posts, and another chuck have less than 5 posts.  There are actually only a few tags that have more than 20 posts (so at least 3% of the total number of posts).  Based on all that poking around, I'd like to suggest the following tags.  **NOTE: This list has been updated based on conversations below**

Community (shown as Community Updates)
Conferences
Deep Dives
DevCon
Developer (shown as Developer Updates)
Prerelease (shown as Prerelease Announcements)
Release (shown as Release Announcements)
April Fools (this is force sorted to the bottom of the list)

We probably have space to have one more tag without making the index pages look strange. So if there are other tags we feel we really want, we can add them. I'd also like to suggest that blog posts not have more than three tags. After three the tag list on the index card almost always wraps to a second line. It's not the end of the world, but it does look funny.

I've tried a few different things to get the old tags out of Drupal, but I haven't found anything that will give them to me. I suspect by the time I write something to map the old tags to the new tags and insert that into the markdown files that we could just go through the 600 blog posts by hand and tag them anyway.

**Comment by ProfYaffle** [comment]
We could perhaps merge _DevCon_ into _Conferences_, which would also then encompass RC3, User Groups, LinuxTag, whatever. I don't have any feeling for what people might search for, and thus whether it muddies the water to mix internal and external conferencing; it might be that nobody really uses the tags anyway (except me, to find old announcements), after all.

We've had long-standing desires to have _Feature Friday_ or similar, in which we could maybe dive into a specific aspect of Kodi. Whether this remains an unattainable goal matters less here than how we'd tag such articles: _Feature_? _Focus_? _Deep Dive_? _Under the Hood_? _Hints and Tips_? We have a couple of _Addon_ focus articles that would fall into this bucket. 

Scrolling through the last few pages of blog posts, and seeing what's there... where would we put sponsor announcements, or calls for donations? _News_? _General_? 

No problem with a limit on multiple tags. It looks like we're perhaps heading for tags-as-category-labels, anyway, in which case most things should really fall into a primary category of some kind.

**Comment by pkscout** [comment]
I saw the Feature Friday tag, and I like that idea if we're gonna do it.  I'd definitely go with something more generic, and I kind of like *Deep Dive*.  I just don't want a tag that has like 2 posts from 5 years ago. I'd say sponsor announcements and call for donations could go under *Community Updates*.  If we add *Deep Dive* and *April Fools*, then we still easily have space for one more tag.  I wouldn't do something like General or News though. That's kind of what the *All News* link is for.  But at the end I really want these to feel right for the folks doing content management. So I'm also OK with scrapping the whole list and using a different one.

And yes, I think the tags now are a bit more like categories, and we could rename them if we wanted to.

I think the tags can be useful (and used) if they have some meaning and are well surfaced on the site. The dropdown box on the current site doesn't really help with that now, especially if you try a couple and find no posts or just a couple of old ones.  It's one of the things I like about the new layout. The tags listed are only those in use, and the number gives you a sense of how much content you'll find there.

**Comment by pkscout** [comment]
I like the idea of DevCon having it's own tag.  I've updated the proposed list in the initial issue post to reflect the addition of Conferences and Deep Dives tags.

**Comment by pkscout** [comment]
I have created a `blog-cleanup` branch and tagged posts going back to 2010 (and some older than that for things like releases).  https://kodi-tv-staging.netlify.app now has the updates from this branch.

**Comment by pkscout** [comment]
The updates have been reviewed and OK'd. Merged with staging.
