### ISSUE TITLE
Link to IRC/Matrix

### ISSUE THREAD

**Issue by yol** [xbmc/kodi-tv#144]
Maybe I just haven't seen it, but shouldn't we link to IRC and/or our Matrix community somewhere? @Razzeee @keithah ?

**Comment by Razzeee** [comment]
We could probably handle that in the footer too, as socials. 

Btw @pkscout I've been thinking to remove the socials from the header completely as I think it's way to prominent and we don't really use them that much/want people to rely on the website if we can choose.

**Comment by pkscout** [comment]
That's fine with me. At this point the social icons are really just filler on larger screens and a little eye candy in the mobile menu anyway. If somebody will post the link for IRC, I'll add it to the footer.  Is that Matrix community something different, or an IRC channel? I guess if we have a bunch of IRC channels we could have a link in the footer for IRC that goes to a page (like `/about/irc` that links to whatever channels we want to highlight.

**Comment by yol** [comment]
> Btw @pkscout I've been thinking to remove the socials from the header completely
+1

I'm not sure about IRC and/or Matrix. Do those warrant being put in the header or only footer? We arguably use them more when compared to the "socials".

> If somebody will post the link for IRC, I'll add it to the footer.
`irc://irc.freenode.org/kodi`

In theory, we do have a multiple IRC channels that I think are not listed anywhere at the moment - `#kodi`, `#kodi-linux`, and `#kodi-dev` (any I missed?). I think it would be fine to list them on an extra site.

Matrix is different from IRC. You can link to `https://matrix.to/#/#kodi:matrix.org`.

**Comment by pkscout** [comment]
Got it, well sort of. That IRC link doesn't work in a web browser.  I'm not an IRC user, but I'm guessing that URL would work in an IRC program. So for IRC it seems like we really do need a page with our IRC information (and maybe some links to IRC programs).  Now I'm thinking we should put it in `/help/irc`. I need to create another Page section in the CMS for help pages, but it wouldn't take that long.

The Matrix link (that is going to get confusing given the name of our current release) at least gets you to a page to download the programs you need.

As to placement, the social list in the header can probably have one more icon added to it (assuming we keep it at all). The footer list can technically go as long as we want, but I really don't want the footer to get any better. So in the footer we have three slots left for social.  **If** we are going to keep the social icons in the header, they should definitely be the ones we feel are most active.

**Comment by keithah** [comment]
So nobody really uses Matrix either, so I don't like the idea of using that.

So there's this irc link that works: https://webchat.freenode.net/#kodi

But the next problem is, #kodi requires registration to join, to avoid spam, which majority of users who click it won't know.

We could have #kodi-intro or something to drop people in with a bot that explains it? Or potentially do a redirect to it for unregistered folks to #kodi-intro when they try to join #kodi unregistered.. I think I've seen freenode do this.

**Comment by Razzeee** [comment]
Yeah, matrix isn't super active, but we never advertised it or even mentioned it in the forum. Still, we get asked questions and actually help multiple users a week. Just judging from the last few weeks.

**Comment by yol** [comment]
> I'm not an IRC user, but I'm guessing that URL would work in an IRC program.

Yes.

> So nobody really uses Matrix either, so I don't like the idea of using that.

Yeah, I concur it's not super active compared to e.g. the forums or IRC even. But the activity level is way above what I expected, that's why I mentioned it.

> But the next problem is, #kodi requires registration to join, to avoid spam, which majority of users who click it won't know.

Exactly, I think that makes the WebIRC link in this form rather useless. People that don't have a regged user can't use it, and people that do have on probably have an IRC client installed anyway.

> We could have #kodi-intro or something to drop people in with a bot that explains it? Or potentially do a redirect to it for unregistered folks to #kodi-intro when they try to join #kodi unregistered.. I think I've seen freenode do this.

That is a way to do it, but it also feels quite involved both to set up+maintain and for the users to get what is going on. Registering a nick is not straightforward at all for people unacquainted with IRC. Wouldn't it be easier to let those people use Element in the browser like on `https://app.element.io/#/room/#kodi:matrix.org`? It at least guides you through account creation. Only problem might be that we have considerably fewer Team Kodi people over there than on the IRC channel (though I haven't counted). All in all, I think in the long run Matrix is a better platform for us to have a public realtime support/discussion channel for user<->user and team<->user.

**Comment by Razzeee** [comment]
I hope, that matrix will become even more useful when it gets spaces later
this year. Might be worth pushing for it at the team meeting. At the moment
we have 5 kodi members in that kodi channel

yol ***@***.***> schrieb am Fr., 2. Apr. 2021, 21:28:

**Comment by Razzeee** [comment]
I think having its own page for it or doing another card on the contribute page is the way to go

**Comment by pkscout** [comment]
I've opened a new issue for the header and footer menu. If we could move the conversation about where to put this to that issue, that would be great.

https://github.com/xbmc/kodi-tv/issues/157
