### ISSUE TITLE
Bring back statistics on frontpage

### ISSUE THREAD

**Issue by Razzeee** [xbmc/kodi-tv#148]
![image](https://user-images.githubusercontent.com/5943908/113486624-21fa2d80-94b4-11eb-9202-bda978520afc.png)

**Comment by pkscout** [comment]
We should probably add the logic for this to the addon-parser script (since it runs every day anyway).  I can have it generate a YAML file with the stats that we can then pull in with a GraphQL query.  Does anyone know where the Github and Forum stats come from?

**Comment by Razzeee** [comment]
I don't think we have an api. These are just hard-coded on the old page.

Kyle Johnson ***@***.***> schrieb am Sa., 3. Apr. 2021, 20:11:

**Comment by pkscout** [comment]
That is so barbaric I couldn't wrap my brain around it.  I found a pretty simple way to get the count of Git commits:

https://gist.github.com/0penBrain/7be59a48aba778c955d992aa69e524c5

And there is a page on the forum that has some stats:

https://forum.kodi.tv/stats.php

With those and a little RegEx Fu, I was able to have the addon-parser grab those stats (and the addon count, which the parser already had) and save them as a YAML file. (see f5161efe8b3c9b69a0eda4c6a9d78721286951cc).  Gatsby then loads them at build so we can use a Static GraphQL query to get them and put them on the main page (see 4d40768e642fce1eb950ddaba71803fdd0b6d041).  There are now vital stats at the bottom of the index page.

**Comment by Razzeee** [comment]
Neat, looks great

**Comment by Razzeee** [comment]
I would like to tinker with https://github.com/inorganik/countUp.js at some later point to make it a bit more dynamic

**Comment by Razzeee** [comment]
Ended up trying https://github.com/vydimitrov/use-count-up which works with some changes, but starting it on visibility would probably need another additional package. Might not be worth it.

**Comment by pkscout** [comment]
It's up to you. I've never been a big fan of that kind of animation anyway, so I'm good without it.
