### ISSUE TITLE
Improve "Kodi does it all" section on homepage

### ISSUE THREAD

**Issue by Razzeee** [xbmc/kodi-tv#150]
It's either too short or should be removed all together.

Another option would be to move the text to the carousel above and find a picture for it.

**Comment by Darren-Hill** [comment]
Personally I'd say remove it, as it's a bit superfluous.

That said if we do, then the section below for me really doesn't work at all. The little icons are very much out of style with the rest of the page (pictures above and larger and much more detailed/colourful icons below). Those icons really don't work for me at all, they spoil the look of the page.

**Comment by pkscout** [comment]
@Darren-Hill, you wound me. That feature section is my favorite.  OK, maybe not my favorite, but it was one of the first ones I managed to do, so give me a minute to morn it's passing.  '-)

We could use the same card that we have for the News at the bottom of the page there. That would actually make it consistent with how the longer list of features is listed on the about page. My concern there is that it will (I think anyway) take even more space on the page and potentially look very busy. But maybe if we get rid of the the "Kodi Does It All" section the space and busy won't matter.  I'll mock something up to look at.

**Comment by Darren-Hill** [comment]
:)

My first thought was the icons were placeholders for something that had failed to load or something. Just looks a bit dull and drab compared to the Android and Pi large colourful logos in the section below it.

**Comment by pkscout** [comment]
The original version of that feature section used the brighter "kodi" color (but still the same icons), but a couple folks thought it was a bit too much. So we muted the colors down. I'll mock that option back up too.

**Comment by Razzeee** [comment]
If we do away with that, the icons in the following sections should be
removed too. We could move them into the click able buttons.

Kyle Johnson ***@***.***> schrieb am Sa., 3. Apr. 2021, 20:48:

**Comment by pkscout** [comment]
> If we do away with that, the icons in the following sections should be removed too. We could move them into the click able buttons.

What next section? I wonder if we're going to end up removing so much that we just have a home page with a bunch of cards and clickable buttons.

**Comment by Razzeee** [comment]
![image](https://user-images.githubusercontent.com/5943908/113491799-ac05be80-94d3-11eb-8d78-d065c4912e75.png)

The icon on top. I think it looks nice on desktop, but they look kinda weird on mobile. So we could just hide them on mobile.

**Comment by pkscout** [comment]
Got it.  With c889d1f1978c26deb9d91cfb8033220f7be06b7e the CTA icon is now hidden on mobile (both for the section you mentioned and the "But wait, there's more" section below it). I also tightened the whole page up vertically a bit on mobile.  There was way too much white space given the amount of scrolling you're going to do on mobile.

**Comment by Razzeee** [comment]
Looks good, the "Kodi is the ultimate entertainment center software"-section still has them. Is that how you want it?

Might be cool to do it like this? Not like the one below?

![image](https://user-images.githubusercontent.com/5943908/113495244-833ff200-94f0-11eb-947f-d97f94d9e415.png)

**Comment by pkscout** [comment]
That's one of the sections that seems to not be getting any consensus in it's current form. I'm going to mock up some options (probably tomorrow for me), so that might go away in it's current form altogether. So there's no sense tweaking it around the edges until we know if we're gonna keep it.

**Comment by pkscout** [comment]
I've done some work to make it easier to move and recolor the various widgets on the home page and  have some new pages people can look at in staging:

https://kodi-tv-staging.netlify.app  
This is the "current" home page with the feature icon section reverted back to it's original (brighter) color.

https://kodi-tv-staging.netlify.app/index-alt-1  
This one removes the first text call out and kind of merges it with the feature list. The feature list is now a set of image cards (basically just like on the about page). I also removed the Help Us section (that's the one with that stupid stock photo image right now).

https://kodi-tv-staging.netlify.app/index-alt-2  
Same as alt-1 but with different colored headers (just to show it isn't hard to restyle them now and see if folks maybe like a bit more color that way)

**Comment by Razzeee** [comment]
Really like alt 1,but only tried on mobile yet.

Kyle Johnson ***@***.***> schrieb am So., 4. Apr. 2021, 22:30:

**Comment by Razzeee** [comment]
Tested on a desktop now, still really like alt 1, some small color changes, I would like to look into, but nothing mayor. (mainly the statistics widget)

**Comment by pkscout** [comment]
I've merged alt-1 into the main page and merged those changes into staging. I think this completes the issue.
