### ISSUE TITLE
Replace android icon

### ISSUE THREAD

**Issue by Razzeee** [xbmc/kodi-tv#151]
It seems a bit broken on the upper lip?

**Comment by pkscout** [comment]
I just figured it was sticking it's tongue out.

¯\_(ツ)_/¯ 

But yes, if you do a search for Android icon, none of the other ones I can find have that notch.

**Comment by Razzeee** [comment]
Yeah, thought the same, then searched :D

Kyle Johnson ***@***.***> schrieb am Sa., 3. Apr. 2021, 20:33:

**Comment by pkscout** [comment]
fixed with faa5f92dc22a70e77ec77a93120c6732b5c93cda. This hasn't been published to the staging site yet, but I'll be done another build soon.
