### ISSUE TITLE
Donor wall has html elements printed

### ISSUE THREAD

**Issue by Razzeee** [xbmc/kodi-tv#154]
https://kodi-tv-staging.netlify.app/donate/wall/

Also the layout could be a bit more consitent/prettier

**Comment by pkscout** [comment]
I'm pretty sure that HTML entity issue is a remanent in the test donor database from some early tries that didn't work right. The AWS database has that same entry in the database. I can probably just delete those test entries to fix that.  I do agree that the layout is not awesome. I could use the Feature Card that is used for add-ons and just use a generic person icon in there with the donor and amount in the main part of the card. It would at least spruce it up some.

**Comment by pkscout** [comment]
Removed bad entries from test db and changed layout to use featured card.  Resolved with 8f199f6096b2ddb9646a2e58f9da6d899bf22f09
