### ISSUE TITLE
Some more ugly pages

### ISSUE THREAD

**Issue by razzeee** [xbmc/kodi-tv#155]
Take this with a grain of salt, just because I think they are ugly, it doesn't have to mean they are, I just think we can improve them:

~~https://kodi-tv-staging.netlify.app/blog/search
https://kodi-tv-staging.netlify.app/addons/matrix/search/
https://kodi-tv-staging.netlify.app/addons/leia/search/~~

Make the links bigger/cards maybe with a good picture?
https://kodi-tv-staging.netlify.app/addons/

I think the links should be more prominent and we might be able to use some logos to guide people more easily?
https://kodi-tv-staging.netlify.app/donate/

~~These need layout/button work:
https://kodi-tv-staging.netlify.app/donate/by-stripe/
https://kodi-tv-staging.netlify.app/donate/by-paypal/
https://kodi-tv-staging.netlify.app/donate/by-patreon/ (such little content, somehow show it nicer)
https://kodi-tv-staging.netlify.app/donate/by-bitpay/
https://kodi-tv-staging.netlify.app/donate/by-wire-transfer/~~

**Comment by yash37158** [comment]
can i work on this issue ?

**Comment by razzeee** [comment]
Sure, but please target staging for merge

**Comment by yash37158** [comment]
Yeah sure

**Comment by yash37158** [comment]
can you please tell me how we can run on the 
local host?

**Comment by pkscout** [comment]
All the documentation for the site (including Gatsby setup) is at:

https://github.com/xbmc/kodi-tv/wiki
