### ISSUE TITLE
RSS feed has no images

### ISSUE THREAD

**Issue by Razzeee** [xbmc/kodi-tv#158]
The new feed when viewed from feedly

![image](https://user-images.githubusercontent.com/5943908/113604092-1427e200-9645-11eb-943d-aaba78a80739.png)

The old one on feedly 

![image](https://user-images.githubusercontent.com/5943908/113604141-26a21b80-9645-11eb-9a87-ae6cb0b0e4d4.png)

It could be due to the feed being new, but I don't think that's the reason

**Comment by Razzeee** [comment]
It's not just the stories, it's also that the old feed has an image/icon, but the new one doesn't

**Comment by pkscout** [comment]
I noticed that issue and used Feedly when I was testing some updates. I think Feedly has hyper-aggressively cached an old version of the RSS feed, and nothing I do will get them to let go of it. So I think this is fixed.  This is what I get in innoreader:

<img width="1504" alt="Screen Shot 2021-04-05 at 8 24 13 AM" src="https://user-images.githubusercontent.com/1402018/113610238-8918fe80-95e8-11eb-9500-026fd552562d.png">
 
And the summary section:

<img width="1504" alt="Screen Shot 2021-04-05 at 8 27 46 AM" src="https://user-images.githubusercontent.com/1402018/113610455-dc8b4c80-95e8-11eb-9e9a-59c4aa7b2b30.png">

**Comment by Razzeee** [comment]
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fkodi-tv-staging.netlify.app%2Frss.xml

While trying to validate this, I found that validator and we get an interesting error. So I checked again in feedly. I indeed have pictures if I click into the article, where we have pictures for them.

But in the case of https://kodi-tv-staging.netlify.app/article/kodi-19-0-matrix-release/ (the one the validator remarks for the t-shirt picture) I don't get the main image. All other images seem fine.

**Comment by pkscout** [comment]
And that t-shirt image problem could still be a cache thing. One of my tests at some point yielded no images for anything except that one post, and it had the t-shirt.

I have a love/hate relationship with RSS.  I love it as a consumer, but as a content creator it makes me want to scream. There is no standard way of doing some basic things (like having a featured image for an item), so you're left trying to find examples other people did that seem to work in most readers/validators.  

I'm not sure what to do about that validation error. The CMS let's you insert relative links in the text via Markdown, and the only way I can think to keep this from happening is to try and come up with a valid regex expression to test for this (widgets can take a pattern for testing). 

https://www.netlifycms.org/docs/widgets

It's either that or write something to run through the article markdown files and try to fix them after they are saved.

**Comment by Razzeee** [comment]
Probably not worth it, let's close this, at least it's documented now

Kyle Johnson ***@***.***> schrieb am Mo., 5. Apr. 2021, 20:59:
