### ISSUE TITLE
Swap out BitPay for New Bitcoin Payment Option

### ISSUE THREAD

**Issue by pkscout** [xbmc/kodi-tv#163]
I just noticed https://github.com/xbmc/board/issues/195 from the board meeting, so I've added this issue so that we can swap out the BitPay page when the new option is ready.

**Comment by pkscout** [comment]
@Darren-Hill do you know anything about the new method for Bitcoin donation? I tried doing some Google searches for the thing mentioned in the team meeting (or maybe board) notes and didn't find anything that would help me understand if this is a new form or just a link to some site where people can donate Bitcoin.

**Comment by Darren-Hill** [comment]
@pkscout - That would be a question for @yol or @keithah . 

They were handling the switchover and know more details than me.

**Comment by yol** [comment]
as far as I am aware @keithah is investigating Kraken. we're still in the verification process and they're asking for loads of paperwork unfortunately :/

**Comment by pkscout** [comment]
Got it. Our Bitpay stuff does still work for now, and I added a note about them now requiring registration, so I think I'll just leave it active and remove the blocker tag from this issue. We can launch with Bitpay and change stuff later.

**Comment by yol** [comment]
OK so we got every.org now which can be used to donate crypto -> https://every.org/kodi

We would like to replace both the Bitpay and the Endaoment link with that since it offers better options. Could you do this @pkscout or @razzeee ?

**Comment by yol** [comment]
This is the correct link: https://www.every.org/kodi#/donate

If we want to use a button, this would be it:
`<div id="edo-donate-btn"><a href="https://www.every.org/kodi#donate">Donate</a></div><script async defer src="https://assets.every.org/dist/donate-button/0.3/index.js" class="edo-donate-btn-js"></script><script>function createWidget() {everyDotOrgDonateButton.createButton({selector: "#edo-donate-btn",fontSize: "18px",});everyDotOrgDonateButton.createWidget({selector: "#edo-donate-btn",options: {nonprofitSlug: "kodi",showInitialMessage: false,defaultFrequency: "once",infoPages: [{key: "faq",name: "FAQ",source: `## How does this donate button work?This button is powered by Every.org, a tax-exempt US 501(c)(3) nonprofit building accessible giving infrastructure to help every person and organization do more good.You will be directed to www.every.org to securely complete your donation. You can donate cash via Bank, Card, Google Pay, Apple Pay, or PayPal. You can also elect to donate Crypto, Stock, or via a DAF.## Is my donation tax-deductible?Yes, your donation will be made to Every.org, a US 501(c)(3) tax-exempt organization with EIN 61-1913297, and you will instantly get a receipt emailed to you.We do not provide legal or tax advise to individuals, but generally speaking in the US if you itemize your tax return, then tax deductible donations can reduce taxable income.## How long does it take for my donation to arrive?Your donation information will be sent instantly and funds are disbursed weekly.`,},],currencies: [{countryCodes: ["US"],name: "USD",symbol: "$",minimumAmount: 10,},],},});}if (window.everyDotOrgDonateButton) {createWidget();} else {document.querySelector(".edo-donate-btn-js").addEventListener("load", createWidget);}</script>`

**Comment by pkscout** [comment]
I can change it.  Actually that page is in the CMS, so technically lots of people can change it, but I would be happy to do that (and will).  Is there a conversation to be had about just replacing all our pay links with this?  It looks like it includes everything we use (credit card, PayPal, bank, and crypto) plus some we don't other ways (ApplePay, Venmo).  I know we'd have to figure out the donor page, but that only works for Stripe and PayPal (some of the time) anyway.

**Comment by pkscout** [comment]
That change is publishing now.  I'm really curious how Every.org stays afloat.  They don't charge us, and they don't charge when a transaction is made, so I think they have a zero dollar model.  Which seems suboptimal to me.

**Comment by yol** [comment]
Thanks! I think we don't want to be too dependent on one provider, so for now we'll keep the other options on the page. We need to keep all the accounts anyway since people have set up recurring donations that we don't want to disturb.
I think the Paypal notifications should be fully working now :)
