### ISSUE TITLE
Check social previews

### ISSUE THREAD

**Issue by Razzeee** [xbmc/kodi-tv#167]

**Comment by Razzeee** [comment]
Seems to need work https://socialsharepreview.com/?url=https://kodi-tv-staging.netlify.app/article/kodi-19-0-matrix-release/

**Comment by pkscout** [comment]
There's some preliminary work on this in staging (and published to the staging site so you can test pages). I've set some default stuff for every page with the ability to override it. So, for instance, the blog posts use their excerpt, title, and image for the metadata.  There is still some stuff to work on like:

1. Twitter wants the description to be no more than 200 characters. The excerpt is currently 300 (which is nice for the other services), so I either need to shorten the excerpt for the metadata to 200 characters everywhere or figure out how to alias the field in GraphQL so I can use it twice.
2. The image is not optimized for the metadata. I can fix that for the default image, but with the blog posts we are stuck with whatever size is uploaded (at least until someone figures out the right incantation for the Black Magic that is Gatsby Image).

**Comment by Razzeee** [comment]
Good enough
