### ISSUE TITLE
Update Foundation page

### ISSUE THREAD

**Issue by pkscout** [xbmc/kodi-tv#17]
Request from @keithah to update the Foundation page. He already volunteered that the Board would help with that.  '-)

**Comment by Darren-Hill** [comment]
@pkscout I've been asked to take up the task to help with the various content items.

I'll get in touch with you sometime next week so we can review everything in that regard to know what I should tackle and how to go about it.

**Comment by pkscout** [comment]
Sounds good.  I guess you drew the short straw.  '-)

**Comment by Darren-Hill** [comment]
Updated version - https://kodi-tv.netlify.app/about/foundation
