### ISSUE TITLE
Drop down bug on Safari

### ISSUE THREAD

**Issue by sy6sy2** [xbmc/kodi-tv#170]
If you use Safari browser (tested on macOS Big Sur) and if you click on any item of the main menu tab with a drop down menu (e.g. Add-ons, About or Help) the drop down menu will open (ok that's fine) but if you click gain on the arrow icon the drop down menu close and re-open immediately.

**Comment by pkscout** [comment]
OK good. I'm not going crazy. I use Safari on OSX and have seen this, but it doesn't seem to be super consistently a problem for me. It almost feels like one of those "you're not clicking it right" bugs. I'll look into it some more.

**Comment by pkscout** [comment]
After further investigation, this bug also appears in Firefox for OSX.  It doesn't happen on Firefox for Windows, nor does it occur on Microsoft Edge (either platform).  I'll file a bug report with the TailwindUI folks (the dropdown is generated with one of their react components).  Interestingly, if you always click on the arrow to the right of the actual text, it seems to work fine. It's only if you click on the actual word that it seems to be a problem.  So I was right. You're clicking it wrong.

'-)

**Comment by pkscout** [comment]
And now after updating Firefox to 88 it works fine on Firefox.  Anyway, I submitted a bug report to TailwindsUI.

**Comment by sy6sy2** [comment]
Strange bug... I come across it by accident after razze message on slack.

**Comment by pkscout** [comment]
The TailwindUI folks have been able to duplicate the issue and are looking into it.

**Comment by pkscout** [comment]
This appears to have been fixed by the TailwindUI folks at some point.  I recently updated the TailwindUI modules, and this problem didn't reappear.
