### ISSUE TITLE
TV Maze- "Friend"

### ISSUE THREAD

**Issue by KarellenX** [xbmc/kodi-tv#171]
TV Maze is a TV Show metadata provider which provide a free API just like TVDB and TMDB. We have a TV Maze scraper that utilises their service. They have also donated to Kodi.

Can we add them as a "friend".
![friends](https://user-images.githubusercontent.com/44626605/115970932-0224c980-a589-11eb-809f-b6942798b97d.jpg)

Do we have a guideline on what constitutes a Kodi "Friend"?

**Comment by pkscout** [comment]
I'm going to ping @Darren-Hill on this one. He's the board member on the web team, so he's probably in the best place to let us know about how the friend list is curated.

**Comment by KarellenX** [comment]
I pinged you in the slack conversation regarding this.

**Comment by pkscout** [comment]
Based on conversations in the Slack channel, we'll add this one. Done with d1431ee6e1c2adb2f8a5041e3f0c32378f73e688. The board will be looking at formalizing criteria for being listed as a Friend in the footer.
