### ISSUE TITLE
Update Netlify Settings and DNS

### ISSUE THREAD

**Issue by pkscout** [xbmc/kodi-tv#172]
In the Netlify settings we need to add the kodi.tv domain (as well as www.kodi.tv) and then enable the SSL site certificate. Not sure what needs to be done on the DNS side.

**Comment by pkscout** [comment]
There are two DNS changes we need to make to transition the site.

Add CNAME record:
<img width="779" alt="Screen Shot 2021-05-09 at 2 51 22 PM" src="https://user-images.githubusercontent.com/1402018/117593095-aa34a980-b0d6-11eb-98b9-1b7e5b47f383.png">

Add A record:
<img width="776" alt="Screen Shot 2021-05-09 at 2 51 45 PM" src="https://user-images.githubusercontent.com/1402018/117593112-b6206b80-b0d6-11eb-9151-c7c8b0e2b78c.png">

**Comment by yol** [comment]
Regarding the settings, I think we've always used `kodi.tv` as primary domain name (as opposed to `www.kodi.tv`) - fine if I change that?

**Comment by yol** [comment]
The settings in the screenshots are fine and not really what I was worried about; maybe I should have been clearer. I've just seen that in Netlify itself you can set something as a "primary domain" and that is set to www.kodi.tv. If you set kodi.tv as primary domain, do the suggested DNS entries even change?

**Comment by yol** [comment]
To clarify, I would still go through Cloudflare, since AFAIK we have free unlimited traffic there. Netlify is limited to 400GB/month. So I might not even set up the entries exactly like they are above, but it should work out in the end.

How about if I just try it out with the staging site (set it to `staging.kodi.tv` or something?) so we can see if all is working OK?

**Comment by pkscout** [comment]
Thanks for the Cloudflare info. I was literally just typing that question.  If we are going to use the Cloudflare CDN, we should reverse the setup so that kodi.tv is the primary and www.kodi.tv is the redirect. I have updated the Nelify config accordingly and confirmed that nothing changed with the above DNS config requirements.

I also enabled a custom domain on staging, and you can do that one any time so we can see what happens. That will let me test the final SSL certificate config too.

`staging CNAME kodi-tv-staging.netlify.app.`

**Comment by yol** [comment]
https://staging.kodi.tv/

should be alright

**Comment by yol** [comment]
SSL is handled by Cloudflare by the way :)

**Comment by yol** [comment]
Done and live!
