### ISSUE TITLE
Downloads on addon pages

### ISSUE THREAD

**Issue by yol** [xbmc/kodi-tv#186]
E.g. on this page:

https://kodi.tv/addons/matrix/plugin.video.documentaryheaven

It's not that intuitive to have to click on "all" at platforms to actually download the zip. Maybe this could be improved in some way, like adding "download" or just a download icon?

**Comment by Razzeee** [comment]
I'm kind of wondering, when you would even use the download there. Might be more of a dev case. But I guess we can still improve it.

I think if we want to go the download icon road, we need a download icon for each platform and one general.

**Comment by pkscout** [comment]
Yea, the multi-platform ones will end up with like seven or eight buttons if we go the button route. We can certainly look at something different, but given that we don't really want folks to download the add-ons that way, I'm also OK leaving it a little obtuse from a UI perspective.

**Comment by yol** [comment]
> I think if we want to go the download icon road, we need a download icon for each platform and one general.

I'm not sure we have to go that far. I was just thinking something like https://fontawesome.com/icons/file-download?style=solid

**Comment by pkscout** [comment]
Changed the download links on the addon detail page so that you get a little download icon in front of it.  Items with different download links per platform now show as a vertical list instead of a comma separated one.  Should be in staging in the next 10 minutes.

**Comment by ProfYaffle** [comment]
Looks okay from what I've seen wandering through addons, e.g.:

Multiple platforms: https://staging.kodi.tv/addons/matrix/game.libretro.retro8

Generic, any platform: https://staging.kodi.tv/addons/matrix/script.keymap

**Comment by pkscout** [comment]
Fixed with c52d4a8bb25d1404901e95e5cb97e3aafa3e7fa7 back in November. Closing.
