### ISSUE TITLE
Submit add-on search with enter key

### ISSUE THREAD

**Issue by exploide** [xbmc/kodi-tv#187]
Great new website! As a minor usability improvement, I would like to propose that pressing the enter key submits the add-on search form. As of now, one needs to click the "Search" button with the mouse.

**Comment by pkscout** [comment]
Fixed and in staging for testing.

https://staging.kodi.tv

**Comment by pkscout** [comment]
Fixed with 7afba8a5250e61c90e01fe26afd2853b9fe51041 back in November.  Closing.
