### ISSUE TITLE
Add information about Netlify hosting

### ISSUE THREAD

**Issue by pkscout** [xbmc/kodi-tv#19]
We need to add the language from our hosting agreement with Netlify to the site footer.  I think I have an email with that information, and I'll post it if I find it, but if someone else has it and can post it here, that would be great.

**Comment by pkscout** [comment]
Found it. It's much less than I thought. Just need to add "Powered by Netlify" to the footer. I think they will also be listed as a sponsor. Someone just needs to confirm the level for me.

**Comment by pkscout** [comment]
Footer has been adjusted to add the needed text. Also replaced Aquia as sponsor in footer with Netlify. The actual sponsor page still needs to be updated and has it's own issue at https://github.com/xbmc/kodi-tv/issues/18

**Comment by Razzeee** [comment]
@yol for the sponsor level

**Comment by yol** [comment]
We would not list them as sponsors, since we do not have a sponsorship agreement. Just leave the footer message in place :)

**Comment by pkscout** [comment]
Removed Netlify from sponsor list with 856a1382fe83f54f15f2596b8650f330b849349f. I'm going to go ahead and close this one.
