### ISSUE TITLE
Feature Request: DMCA section/notice

### ISSUE THREAD

**Issue by keithah** [xbmc/kodi-tv#2]
something like:
https://addons.videolan.org/terms/dmca is legally required, according to JB, so it'd be great to have a page for this, maybe in addons? Not sure where it should be linked/etc, but at least indexed/googlable.

**Comment by pkscout** [comment]
We have a GPL Violators page in the footer that is technically in the about section (but not in the submenu), so maybe something similar for DMCA information (another footer link and a page in about)? Does someone need to do the actual language, or can we just use the one from VideoLAN? We minimally have to change the contact information. I'm pretty sure we can't send our DMCA requests to the VideoLAN folks.  '-)

**Comment by Darren-Hill** [comment]
First draft page is completed, based on the VideoLAN one linked above.

I'll share it with @pkscout for upload so that everyone to review.

I also note that we don't have a Terms of Service notice/page either. I'll add that to the list of things to do...

**Comment by Razzeee** [comment]
Page was moved to https://kodi-tv.netlify.app/about/dmca/ but it's still not linked anywhere.

**Comment by Darren-Hill** [comment]
@Razzeee Yeah, the plan was to get the backend stuff sorted out, then maybe reshape the menus to add this plus Doxygen docs and the wiki link as a new sub-menu in place of the current wiki link.  

Likewise the TOS page needs linking in somewhere as well. Both are newly written pages.

**Comment by pkscout** [comment]
The Doxygen stuff at least has been fixed. There is now a single **Get Help** menu that has the forum, wiki, and doxygen links.  And when the Get Help menu collapses to the **More** menu on mid-sized screens, there is a page in `/gethelp/index` that has those same links/descriptions.

**Comment by Razzeee** [comment]
Does this really need to be in the header? Maybe just footer might be good enough? Or even just a sub page?

**Comment by pkscout** [comment]
I've opened a new issue for the header and footer menu. If we could move the conversation about where to put this to that issue, that would be great.

https://github.com/xbmc/kodi-tv/issues/157

**Comment by Razzeee** [comment]
Closing, as it got it's place in the footer now
