### ISSUE TITLE
Set a minimum donation amount

### ISSUE THREAD

**Issue by yol** [xbmc/kodi-tv#208]
On the old web site, we made $5 (or whatever currency) the minimum donation amount because otherwise too much of the money gets eaten by fees. I think we should reinstantiate this for PayPal and Stripe.

**Comment by pkscout** [comment]
I've figured out a way to do it for Stripe. The PayPal form is going to take a bit because, ironically, it's a simpler form.  It's going to take me a bit to get the dev environment running on my laptop again (I haven't launched it practically since the site launched), but I'll try to get to this in the next few weeks.

**Comment by yol** [comment]
No worries! Thanks for looking into it :)

**Comment by pkscout** [comment]
There is now a fix in staging that will not allow a donation below $5 USD to Stripe or PayPal.  It dynamically updates the threshold based on currency (i.e. if you change to Yen the minimum donation is 500 Yen).  You can take a look at it at http://staging.kodi.tv

**Comment by pkscout** [comment]
Just FYI, the recurring PayPal form will give you an error at the PayPal dev site when you submit a recurring donation. The one time submission works fine. It's been like that since the beginning in staging. Both work fine in production.  I have no idea why it doesn't work in staging.

**Comment by ProfYaffle** [comment]
Without testing a donation, the *Donate* button does indeed appear to scope in and out based on selected numeric value and currency.

Triggers on integers and decimals (e.g. 4.99 doesn't work, 5 does, 5.00 does).

Ignores leading zeroes, so 00005 == 5 == 5.00.

**Comment by pkscout** [comment]
Fixed with 7a5f1aeb098580c3d57123c6068d01a2cfe33a32 back in November.  Closing as complete.
