### ISSUE TITLE
Eslint Errors 

### ISSUE THREAD

**Issue by krishna8421** [xbmc/kodi-tv#233]
Hey,
   I was playing around with the codes and I found there are many Eslint Errors (3000+), most of them can be fixed by turning the rules off but approx 30-40 err are due to variables not defined. Also, eslint is not implemented fully(.eslintignore is not there due to which it is also checking the node_modules folder).

These are not required in the .eslintrc.js file as we can only use "prettier".
    "prettier/@typescript-eslint",
    "plugin:prettier/recommended",

Things I want to do:-
- Update the Packages
- Add .eslintignore
- Fix the Eslint errors by turning off the rules(For now) cos we can't fix all the 3000 lint err at once
- Add husky (git hook)

**Comment by razzeee** [comment]
I think turning off the rules is worse then showing them, like this you can at least get the feedback if you choose to. Otherwise you won't even see it.

I'm a big opponent of husky/git hooks. They are always problematic in my experience.

**Comment by krishna8421** [comment]
I am not saying to turn off the rules permanently, Just muting them for the git flow to work fine and then work on them, because fixing thousands of linting err are much harder, better to fix them one by one.

and husky won't be a problem just a simple bash script to check prettier and eslint before committing codes


I also have some doubt:

[kodi-tv/scripts/addon-parser/app.js](https://github.com/xbmc/kodi-tv/blob/main/scripts/addon-parser/app.js)
225:22  error  'addonstatspath' is not defined  no-undef
253:9   error  'cat' is not defined             no-undef
282:3   error  'newauthor' is not defined       no-undef
283:3   error  'authorcheck' is not defined     no-undef
301:48  error  'newcategory' is not defined     no-undef
307:7   error  'categorycheck' is not defined   no-undef
and some more....

Are these on purpose??

and 

[by-paypal.tsx](https://github.com/xbmc/kodi-tv/blob/2413086356b090876e42e00ed995129eecefd4bd/src/pages/donate/by-paypal.tsx#L18)


var value = target.value; 

this var is also giving a linting err, is this on purpose

**Comment by razzeee** [comment]
> and husky won't be a problem just a simple bash script to check prettier and eslint before committing codes

which means you have to wait for the compile/check on commit, which is annoying/ breaking everybodys flow
you also can't do WIP commits anymore, as you need to fix everything to be able to commit/push

**Comment by krishna8421** [comment]
Husky doesn't start automatically, you have to run 
```
npm run prepare
``` 
else it will act as normal.

In my opinion, it is good to check if the files are ready to commit and the build is successful.

I will make a pull request in  few mins please check it and delete the things you don't like.
