### ISSUE TITLE
Endaoment donation

### ISSUE THREAD

**Issue by yol** [xbmc/kodi-tv#242]
People can now donate in crypto via Endaoment: https://app.endaoment.org/orgs/474565769

Guess it would be good to add a link?

**Comment by pkscout** [comment]
Should it be in addition to Bitpay or instead?

**Comment by yol** [comment]
Let's just have it in addition as far as bitpay still works

**Comment by pkscout** [comment]
Added Endaoment link on the donation page and renamed the Bitcoin section to Cryptocurrency so that we can just the two ways we take crypto.  It's live in production now.  If you aren't seeing the change, you might need to clear your browser cache.
