### ISSUE TITLE
Problem with Addon History Persistence in Netlify Build Environment

### ISSUE THREAD

**Issue by pkscout** [xbmc/kodi-tv#27]
OK, this one is a little sticky and will require some conversation.  Here's some background:

In order to have a list of recently added or recently updated addons, the build process has to have some sense of history. So beforethe repo addon.xml is parsed and converted for Gatsby, a history file is read (assuming it exists), updated, and written back out. That has worked great during testing because all the builds have been done on my machine, and I push the history file to the repo.  Related to that, the script also downloads all the needed images from the mirror site (whether that is really needed is part of the conversation).

Fast forward to testing Netlify builds. I had assumed that if a file was changed during build that Netflify would push it back to the Github repo.  It doesn't (and I think it was naive of me to think it would).  That means anytime we build on Netlify, it uses the most recent history file from the GitHub repo. That's fine while I'm updating the repo regularly, but if I stop the history file will basically get "stuck" in the past.  I can think of three ways to deal with this:

1. Have a VM somewhere that builds the site locally every day and then pushes the updated history file and any new images to the repo.  We'd still use Netlify for continuous deployment, and the update to the repo would trigger a site build (which takes about 5 minutes, so we can do one every day and only use 150 build minutes a month).  With this option blog posts could go live "immediately" upon save because we'd still be using Netlify's continuous deployment option.

1. Have a VM that every 6 hours or so pulls the current repo (this would get any blog posts), builds the site, updates the repo if it needs to (which it would if the addon history file changes), and then pushes the build to Netflify if either there was data that was pulled or pushed to the repo. With this the site wouldn't necessarily rebuild every 6 hours, but it would if needed. That would mean blog posts that are saved could be delayed up to 6 hours.  Good news with this option is that we no longer use any Netlify build minutes.

1. Rewrite the script to grab the history file from somewhere else and then save it back to that same location. I can easily grab a file from somewhere else, but it isn't clear how I'd save the file back using React. With this option the script would have to be changed to save image paths that reference the mirror server rather than local images. I'm not sure what that impact means, but it is an impact. We'd also probably want to figure out a way to schedule a daily rebuild of the site to make sure new/updated addons get added to the web site.

Any of these options will require some kind of external resource, although not a huge one.  I'm open to any of these or other solutions I haven't thought of. BTW, I haven't marked this as a blocker because I can keep the history file up-to-date by hand for now, and as long as I do it once a week it should be fine.

**Comment by Razzeee** [comment]
I think building the page with github actions and then using an action like this https://github.com/ad-m/github-push-action to push the change back to github might work.

**Comment by pkscout** [comment]
That does look promising. Do we have any kind of limits on the github actions we run? The action would have to download npm, install gatsby, grab the site from the repo, install the dependencies, build the site, and then push changes back. It would probably take about 10 minutes of build time total (5 for all the pre-site stuff, then 5 for the actual build).

**Comment by Razzeee** [comment]
We don't have build minutes, they are free. It should also be way faster,
let me build the pipeline.

**Comment by pkscout** [comment]
Completed with 4674c90458081ca93f18b78704f9e4ebe4e409b3. I also added some documentation to the wiki about the action as well.
