### ISSUE TITLE
Jiotv not working with new version

### ISSUE THREAD

**Issue by pralaymitra** [xbmc/kodi-tv#297]
If we are trying to play.its giving flash and stopped.
I tried to install old version after all installation process.
Tried to play jio in that old version.but that time also not working.but after that when trying to upgrade to current version then everything is fine and playing.

But if clear cache of jio or Kodi clear cache automatically itself then gone.everything back to where we start form. 

I appreciate the software and you guys but pls check the issue.

**Comment by pkscout** [comment]
Are you trying to report a problem with the web site, or the actual software?  If this is for the actual software, your best avenue for support is to use our forums at:

https://forum.kodi.tv

It seems like maybe you are asking about an add-on for JioTV.  There doesn't seem to be an addon in the Kodi repo to do that, but I did find this:

https://github.com/Kvijay199428/kodi.repo.jiotv

So maybe that's what you're using?  If so, you should contact the author directly, as there might not be anyone in the forum using it.
