### ISSUE TITLE
Addon on kodi.wiki but not on kodi.tv

### ISSUE THREAD

**Issue by Space2Walker** [xbmc/kodi-tv#3]
Hi,
i'm not sure that is the right place for the issues, but i don't know where would be.

My Addon is listed on [kodi.wiki](https://kodi.wiki/view/Add-on:DNS_Leak-Test) but not on [kodi.tv](https://kodi.tv/show/plugin.program.dnsleaktest) this results in a broken link on wiki.

**Comment by pkscout** [comment]
This isn't quite the right spot (this repo is for the new site we're developing), but I'll see if I can look into the issue.  I know the addon part of the old site can be a little finicky, so I'm not sure what I'll be able to do to fix this.

**Comment by Space2Walker** [comment]
@pkscout 
Thank you for looking into it,
if you can't get it working on the current site, i will wait for the new Site to be realest.
The only thing bothering me is that i don't see the download numbers, to get feedback on my add-on usage.

**Comment by KarellenX** [comment]
https://mirrors.kodi.tv/stats?downloadstats&filter=plugin.program.dnsleaktest-1.1.zip

**Comment by Space2Walker** [comment]
Thanks @KarellenX , this has the info's i wanted.
