### ISSUE TITLE
Check how to replace feeds

### ISSUE THREAD

**Issue by Razzeee** [xbmc/kodi-tv#34]

**Comment by pkscout** [comment]
With https://github.com/xbmc/kodi-tv/commit/44b85e4422e4f921c9d9787337a543295547e955 there is now a RSS feed at /rss.xml. It has the last 20 posts, and we can change that in gatsby-config.  The current template points to the Feedburner feed that the current site is pointing to, so assuming we are still using that Feedburner feed, we can update that setup to use the new RSS feed once we go live.

**Comment by yol** [comment]
I think Feedburner is pretty much dead. Can't we just point directly to /rss.xml?

**Comment by pkscout** [comment]
Yea, that's an easy enough change.  I'll do that at some point in the next few days.

**Comment by pkscout** [comment]
With 280b3ea8c085bc6bcf385edfd43852736afb23fd RSS feed now point to local rss file instead of feedburner.
