### ISSUE TITLE
Set Default Sort of Blog Posts in CMS to Most Recent At Top

### ISSUE THREAD

**Issue by pkscout** [xbmc/kodi-tv#40]
As I'm testing, I've noticed that when I load the Netlify CMS that the blog posts default to sorted alphabetically. To get the most recent posts I have to sort by Publish Date and then reverse that order (because it defaults to oldest first). So it takes at least two sorts to get to the recent posts. That's not ideal, and I'd like to see if there is a setting option to set a default sort order.

**Comment by Razzeee** [comment]
Are you sorting in graphql?

**Comment by pkscout** [comment]
This is in the actual Netlify content editor, not the display of posts. On the display, yes, sorting is done in GraphQL.

**Comment by pkscout** [comment]
I can't quite tell yet, but this might not be possible. I did find a closed Github issue about sort order, but it implies that as of March 2020 the Netlify CMS should default to showing the most recently updated posts first (using Git commits). But our install isn't doing that.

https://github.com/netlify/netlify-cms/issues/54#issuecomment-597718618

**Comment by pkscout** [comment]
Good news. Apparently the production CMS code got updated, and reverse chronological is now the default order. It takes a bit longer to load the list of posts, but I think it's worth it.  I'm going to close this.
