### ISSUE TITLE
Side Bar Close button navigates with cursor (on Window Shrink)

### ISSUE THREAD

**Issue by ShubhamChaudharyy** [xbmc/kodi-tv#44]
Currently if you shrink Kodi.tv website then the hamburger icon SideBar's Close button travels from top to bottom with cursor Dragging.
Ideally it should stay as it is.
Illustration of issue:
![Kodi_issues_with_sideBar](https://user-images.githubusercontent.com/43263087/106390333-e38db700-640d-11eb-8a29-27fe836e11b7.gif)

Would you like to work on this issue ?
Yes

**Comment by pkscout** [comment]
This repo is for the new version of the web site we are working on, not the current web site. We are hoping to roll it out in the near future and aren't doing any fixes on the current web site. I'm going to go ahead and close this issue.
