### ISSUE TITLE
add tvOS to the list of supported platforms on the front page

### ISSUE THREAD

**Issue by kambala-decapitator** [xbmc/kodi-tv#45]
currently only macOS and iOS are mentioned:
![Screenshot 2021-02-19 at 21 53 49](https://user-images.githubusercontent.com/1557784/108548499-f4d72e80-72fc-11eb-92bf-f989bd86434d.png)

**Comment by pkscout** [comment]
Please review the current test site at https://kodi-tv.netlify.app. That change has already been included.
<img width="1505" alt="Screen Shot 2021-02-19 at 8 55 50 AM" src="https://user-images.githubusercontent.com/1402018/108548847-75ac1100-7290-11eb-98d0-af70020e6a42.png">

**Comment by kambala-decapitator** [comment]
sorry, I thought it's WIP and won't be available in the nearest time. Should I close the issue then?

**Comment by pkscout** [comment]
Ah, I see the confusion.  The new site is a WIP, and this is the repo for that.  For the current site I guess the best place to open issues is at https://github.com/xbmc/drupal/issues.  I'm not sure who might be monitoring or working on that though.

**Comment by KarellenX** [comment]
I have added a fix to the current site...
![tvos](https://user-images.githubusercontent.com/44626605/108556992-f9770380-734b-11eb-8f73-99493e6de474.jpg)

This issue can probably be closed

**Comment by ProfYaffle** [comment]
Also added to text on https://kodi.tv/download

**Comment by kambala-decapitator** [comment]
@KarellenX @ProfYaffle great, thank you!
