### ISSUE TITLE
Terms of Service Page

### ISSUE THREAD

**Issue by Darren-Hill** [xbmc/kodi-tv#49]
We're lacking an overarching terms & conditions of service page, which is probably needed as an anchor for stuff like DMCA and the privacy policy.

I'll put one together.

**Comment by Darren-Hill** [comment]
Draft page - https://kodi-tv.netlify.app/terms-of-service

**Comment by Razzeee** [comment]
Moved to https://kodi-tv.netlify.app/about/terms-of-service/

**Comment by Razzeee** [comment]
Should this be linked to anywhere?

**Comment by Darren-Hill** [comment]
Yes, both it and the DMCA pages are new and so far not linked in.

There was some plan to make a new menu or sub-section under the help area for it, but it wasn't finalised as to what went where between the header menu and the footer bar.

**Comment by pkscout** [comment]
I've opened a new issue for the header and footer menu. If we could move the conversation about where to put this to that issue, that would be great.

https://github.com/xbmc/kodi-tv/issues/157

**Comment by Razzeee** [comment]
Closing, as it got it's place in the footer now
