### ISSUE TITLE
Add links under iOS how to install

### ISSUE THREAD

**Issue by keithah** [xbmc/kodi-tv#5]
In addition to the wiki link, we could add in the work @sy6sy2 has done to get jailbroken devices working:

> FYI, all jailbroken users can now install Kodi from Cydia, Zebra, Installer or Sileo without any manual steps. This is the packages available on theBigBoss repo:
>Kodi-iOS (64-bit) --> Kodi 18.9 for 64 bits devices with iOS >= 9.0
>Kodi-iOS (32-bit) --> Kodi 18.9 for 32 bits devices with iOS >= 9.0
>Kodi-iOS (Legacy 32-bit) --> Kodi 17.6 for 32 bits device with iOS < 9.0

**Comment by sy6sy2** [comment]
A new line with something like "**If your device is jailbroken just open your favorite package manager and search for Kodi in the BigBoss repository**" should be enough I guess 😉 

If needed, the user will find detailed information in the iOS wiki page.

**Comment by pkscout** [comment]
Fixed with a8d1cd3aca1bebeba8cd5c5004cf475e86aa8986. I'll leave this open and add the testing label. You can see the change at https://kodi-tv.netlify.app/download/ios.

**Comment by pkscout** [comment]
Having heard no negative feedback, I'm going to close this.
