### ISSUE TITLE
Blog Posts: "Live" View Link Wrong?

### ISSUE THREAD

**Issue by ProfYaffle** [xbmc/kodi-tv#52]
If I look at a blog post, there's an option to launch a live view of the post. However, this returns a 404, as the link appears to be both missing part of the path to published articles and has a different "filename".

Example:

![image](https://user-images.githubusercontent.com/6093716/109392873-7854d900-7916-11eb-8e2a-b4510fe620ec.png)

... links to https://kodi-tv.netlify.app/kodi-19-0-matrix-release-index:

![image](https://user-images.githubusercontent.com/6093716/109392927-e6999b80-7916-11eb-9d75-5956eb253329.png)

... but the blog post is actually at https://kodi-tv.netlify.app/article/kodi-19-0-matrix-release/:

![image](https://user-images.githubusercontent.com/6093716/109392909-b8b45700-7916-11eb-856d-be012f4e2025.png)

**Comment by pkscout** [comment]
The Live view requires a different setup for Netlify builds that I haven't looked at yet.  I'm pretty sure I know what needs to be done though, so it shouldn't be too hard to fix.

**Comment by pkscout** [comment]
I was thinking of two different things. I've fixed the live link in the CMS with 3692235d5b035985fdd44fe8d3d461195720dd3f.  If we want to have preview links that show unpublished drafts in the context of the site, that requires a different way of building stuff on Netlify.  Again, I think I understand how that works, and if it's really important to be able to have unpublished stuff fully previewed in the site, I can get that done.  I'll leave this open for now.

**Comment by pkscout** [comment]
I'm going to go ahead and close this. We can discuss live previews of unpublished stuff later if needed.

**Comment by ProfYaffle** [comment]
I know you've closed, but a final comment from me: it is difficult to see the final formatting until you publish, which is a process that takes several minutes as the website rebuilds, so correcting a mistake or trying different formatting if something goes wrong isn't a quick process, especially if it needs multiple iterations. The alternative would be to write everything on a local instance first, which is unreasonable for most contributors.

Let's see how it works in reality, then - it might be that simple formatting will port across nicely, or maybe there's some frig through which we can say "temporarily apply live website CSS" - but let's establish that it is a problem first.

Thanks for all the work.

**Comment by pkscout** [comment]
Agreed. I've opened issue #80 for that.
