### ISSUE TITLE
Provide download button for Apple Silicon (arm64)

### ISSUE THREAD

**Issue by enen92** [xbmc/kodi-tv#586]
As far as I can tell the current stable version (nexus) is not available for arm (only a single executable that runs under Rosetta on arm).

Omega will bring releases specific to newer Macs so ideally we should have buttons for pre-release and nightly builds targeting "Apple Silicon (arm64)" apart from x86_64 just like those available for Android.

**Comment by pkscout** [comment]
All that can be added using the CMS.  There are no code updates require for that to happen.

**Comment by enen92** [comment]
@pkscout who can add it via the CMS? I don't think I have permissions/access/account there.

**Comment by razzeee** [comment]
You need to use your github account and access to this repo

**Comment by enen92** [comment]
> You need to use your github account and access to this repo

<img width="953" alt="image" src="https://github.com/xbmc/kodi-tv/assets/7375276/738e55ce-5a17-4036-9502-5f1a9729c3b0">

What do I need to do to have access to the CMS?

**Comment by KarellenX** [comment]
@enen92 
I can try adding the button a bit later.
Is this the download link... https://mirrors.kodi.tv/snapshots/osx/arm64/
For the icon, just use the same grey apple symbol as for macOS, iOS and tvOS?
The name is Apple Silicon? or something else?

**Comment by enen92** [comment]
Which icon @KarellenX? I'd suggest something similar to android:
<img width="1212" alt="image" src="https://github.com/xbmc/kodi-tv/assets/7375276/0b7371e9-1003-48a0-9290-ef90ba260125">
So this is just a new button in the already existing macOS download page.

For the buttons label maybe:

`Intel (x86_64)` (note: the existing one)
`Apple Silicon (arm64)`

The download link is correct (for snapshot). For nightlies: https://mirrors.kodi.tv/nightlies/osx/arm64/master/

**Comment by KarellenX** [comment]
>So this is just a new button in the already existing macOS download page.

Oh, ok. That is simple. I thought it was a new platform button. 
(Placing something called Apple under Android is a bit confusing though?)

I'll do that now.

>For the buttons label maybe:
Intel (x86_64) (note: the existing one)
Apple Silicon (arm64)


Sorry, I am not sure what this is... **Intel (x86_64)** is this the new label for the ARMV8A (64BIT)?

The new button will be named **Apple Silicon (arm64)**
and this links to the nightlies and snapshot links above.
