### ISSUE TITLE
Change Wiki link to Documentation and add other documentation sources

### ISSUE THREAD

**Issue by pkscout** [xbmc/kodi-tv#59]
I pulled this from the Drupal issues at the request of @enen92.  This seems reasonable to me in concept.  If anyone has any concerns or thoughts, let me know.

---
Raising awareness for one issue that I think it could be improved. We basically have two sources of documentation:

    Wiki (user maintained and mainly directed towards kodi use although the number of development-based pages). URL: wiki.kodi.tv
    Doxygen (technical documentation kept close to the codebase - in the future it is likely that we'll see more and more content making the transition from the wiki to doxygen). URL: docs.kodi.tv

Our website only links to the wiki. Ideally it should have a "Documentation" header item that would "unfold" to "Wiki" and "Technical docs" (or other).

**Comment by Darren-Hill** [comment]
That makes good sense to me too. The header width may be getting a bit large then, but even on my 4:3 crappy old ex-work monitor it should still fit fine.

**Comment by pkscout** [comment]
Resolved with 363f88b30d95813a0f381a30600ed05c2eea2fa3.
