### ISSUE TITLE
CRT shader

### ISSUE THREAD

**Issue by Shimmer2** [xbmc/kodi-tv#709]
I hope to support the CRT shader, which is very blurry when playing 480p old movies. I really need this feature! Thank you!!

**Comment by KarellenX** [comment]
@Shimmer2 

You have posted to the wrong repository.

If you are making a Feature Request for the Kodi media centre, then please do so in the forum here... 
https://forum.kodi.tv/forumdisplay.php?fid=9

I'll close this issue.
