### ISSUE TITLE
No Dolby Atmos

### ISSUE THREAD

**Issue by gvandesompel** [xbmc/kodi-tv#787]
Hello, I've noticed over the past few days that Kodi on Android TV, for movies and series that I watched in Dolby Atmos, is now outputting in standard audio, so without Atmos. 
My TV is an LG OLED TV and Samsung soundbar. I hadn't changed anything in the settings of Kodi and the Android box.
When it occurred, or when I noticed it a few days ago, I was using the Android TV box ( Nokia 8810 Streamviewer) with the build kodi-20.3-Nexus. 
When I play movies through the Netflix app or even another player ( CX Explorer) on the Android box, I get Dolby Vision and Dolby Atmos. But when I play the movie (network drive) with Kodi, there's no Dolby Atmos.

**Comment by razzeee** [comment]
Please raise this in the forum.

**Comment by razzeee** [comment]
You're probably looking for https://github.com/xbmc/xbmc 

This is the code for the website www.kodi.tv
