### ISSUE TITLE
Blog Post Layout/CSS Observations

### ISSUE THREAD

**Issue by ProfYaffle** [xbmc/kodi-tv#79]
Nothing in any way fatal, just some thoughts...

1. Perhaps force the preview images to be the same size?
2. The date/author/wordcount/reading time seems oddly-spaced (style _pf-c-list pf-m-inline_?) - it has a top margin of -5px, which cramps it into the heading, but then is very widely-spaced, so it's like some kind of ultra landscape view.
3. The text preview probably isn't enough to, well, preview anything - certainly not on a decent screen.
4. The posts could do with better delimiters between them: either more space, or a hard line. Maybe if the title and word count were both *above* the image?
5. I wonder if the article titles could also link to the body text, not just the _read more_ link
6. Tags to show the topic, as per https://github.com/xbmc/kodi-tv/issues/57

**Comment by ProfYaffle** [comment]
Actually, comparing to the existing site... the preview text is the same word count, I think, but the view in Gatsby is wider, so it simply looks like a shorter preview. Might be an artefact of the responsive layout.

Similarly, the article headers on Drupal are better laid-out to my eye: icons, not bullets, between the date, author, etc; article tags, heading link, whitespace between articles, article headers separated from text with a dotted line. It all makes it more readable, and less of a slab of text.

**Comment by Razzeee** [comment]
I think it would be way better to have these split into their own issues, that way we could discuss them and maybe act. I think we were planning on doing some css/html work at some point. (if I can motivate myself)

**Comment by pkscout** [comment]
Agreed about splitting them.  In the meantime though, I have started a little work to try and address some of them.  I think I've attacked all but the first and last issue (image size and tags).  I think there's space now for tags too (which sort of gets at the last item).  Here's a sneak peak:

<img width="1499" alt="Screen Shot 2021-03-01 at 12 07 43 PM" src="https://user-images.githubusercontent.com/1402018/109566528-174d1280-7a88-11eb-81d3-ea3e97bd28f8.png">

**Comment by pkscout** [comment]
The first one I'll need some help on.  I can only get the image to resize responsively if I set a maxheight of a certain number and maxwidth to a percent. And that means if the originals are differ in aspect ratio (and we're all over the place on image ratios on the blog), then they appear different sizes.

**Comment by ProfYaffle** [comment]
Thanks for these - a marked improvement already, IMO. 

I suspect the main cosmetic issue now is simply tying to use the full width of the display because there's no "sidebar" content, or limits to keep it all centrally in a single column. As such, the line and text will naturally wander off to a wide, ragged right margin.

Re: image sizes, understood - unless there's some kind of crop/viewport, which is how Drupal handles it (set a focus point, and then crop around that for the previews). Maybe it's easier to try to enforce a new standard from this point, although that does require people (a) to remember and (b) to perhaps edit their source images. Standard 16:9 HD aspect ratios wouldn't be unreasonable, though.

As for splitting out these and other issues - sure, whatever's easiest.

**Comment by pkscout** [comment]
I've submitted issue #82 to capture the first issue.  The last issue already has an issue open.  I think the rest of the issues have at least been kind of addressed.  I'm going to close this issue just to keep things manageable.
