### ISSUE TITLE
Add download stats to download detail pages

### ISSUE THREAD

**Issue by pkscout** [xbmc/kodi-tv#8]
Need to get the addon download stats from the mirrors server.  Example URL:

http://mirrors.kodi.tv/addons/matrix/script.module.trakt/script.module.trakt-3.1.0+matrix.2.zip?stats

**Comment by pkscout** [comment]
I have code done for this, but so far it fails for an unknown reason when it has to update more than a few addons. More investigation will be needed.

**Comment by pkscout** [comment]
Now that the process for parsing the addons.xml file is separate from Gatsby, I think it will now be possible to add download counts. But they would be download counts for the current version, not all time download counts. Part of that is technical (there isn't a great way to store the historical count and then make sure you aren't double counting stuff), but I would also argue that downloads of the current version are a better reflection on popularity.  If I download and keep using an addon, every time an update comes out, it will update. So the current download count is a reflection of active users.  Using a historic count, every time an add-on updates, it's historic download count will sky rocket. So an add-on that was popular once might always end up at the top of list because of three or four versions of big download numbers. New entries will never make the popular list if they have to overcome 10 years of history of downloads.

**Comment by KarellenX** [comment]
>but I would also argue that downloads of the current version are a better reflection on popularity

Yes I agree. What was popular or working 5 years ago, may not be the case today.

**Comment by pkscout** [comment]
done with a0e21f47a2df7774b3689d367b5d46ef09bc0972 and fc515a6c3284d70792e2612b3430a58737d37bca. I'm going to leave this open for a couple days to see if there's any feedback.

**Comment by wsnipex** [comment]
So you are asking mirrorbits for downloadstats of _every single addon_?

**Comment by pkscout** [comment]
Yes. That seems to be the only way of which I'm aware to do it. It's only happening once a day via the script in the GitHub action. It doesn't feel ideal, and if there's another way to get the stats, I'm open to changing this. Or even reducing the frequency to every couple of days or even once a week if needed. BTW, it takes about 5 minutes to get all the stats for one repo branch (so about 10 minutes to get both Leia and Matrix).

**Comment by wsnipex** [comment]
that sounds like a DOS attack on mirrors :( When did this last run?
Too bad we don't have decent monitoring there atm, would be interesting to see the load this causes.

Generally, I don't like this and we should look for a better solution, e.g. doing a redis export, which at least wouldn't impact mirrorbits that much.

**Comment by pkscout** [comment]
I ran the script once on my laptop maybe 12 hours ago. The run from the GitHub action went around 2:36AM UTC (or it finished around there after 10 minutes, not sure which).  I completely understand your concerns.  I'm unfamiliar with mirrorbits or what doing a redis export entails.  Can that be done on a schedule and put somewhere that a Github action can get to it? If so, and if I can get a sample export for Matrix (and Leia if possible), then I can figure out how to parse and use that instead.  If not that, I can look at introducing a pause between requests to make the load less spiky.  Honestly, whether the job takes 10 minutes or 4 hours doesn't matter all that much.  I do see that Github limits a job run to 6 hours before killing it, so if we have to go that route we just have to keep that in mind.

**Comment by Razzeee** [comment]
The current website already does this every 24h afaik

**Comment by wsnipex** [comment]
how about http://mirrors.kodi.tv/.stats/redis_file_stats_20210308.json
We can quite easily export this every day

**Comment by pkscout** [comment]
@wsnipex That's a good start, and I could definitely use that instead.  The URL I'm using right now:

http://mirrors.kodi.tv/addons/matrix/script.module.trakt/script.module.trakt-3.1.0+matrix.2.zip?stats

gives daily, monthly, and total downloads for the given file. Since we're planning on have the download stats be "of the current version" and not cumulative, the total one is of most interest.  I think the JSON you linked to has the daily downloads.  Could I get one that has totals instead and have the file named the same thing every time?

**Comment by wsnipex** [comment]
There is no "all downloads since the dawn of time" key in the DB, but we have "downloads since start of year".
http://mirrors.kodi.tv/.stats/redis_file_stats.json

Currently there is only 2021, since we started fresh, so you have to be prepared to accumulate years yourself when 2022 comes.

**Comment by pkscout** [comment]
I can work with that.  Thanks.

**Comment by pkscout** [comment]
@wsnipex I have updated the script with PR 89db9ac2054742145cedf308a8f3d04df287cea1 to grab the summary file from the URL you provided.  At your convenience could you set that file to be updated daily and let me know when it's scheduled? Then I can update the run time on the parsing script if needed so that we get pretty fresh data.

Thanks both for pointing out the issue and helping with the solution.  I appreciate it.  And the script only takes like 45 seconds to run now instead of 5 minutes.

**Comment by wsnipex** [comment]
I've added a job that will export to the same file at 0:10 UTC and 12:10 UTC. Shouldn't take more then a couple of min.

**Comment by wsnipex** [comment]
just for completeness: the export contains all files, not just addons. I thought that might be useful for something, but if only addons are of interest, I can probably filter for that.

**Comment by pkscout** [comment]
I don't think the extra stuff will matter that much. I pull that JSON in and then do matches on the path to get what I need, so the extra stuff will just get ignored.  I will take a look at the file and see if any of the other stuff might be useful though.  Thanks again.

**Comment by Razzeee** [comment]
That's actually a neat idea
