### ISSUE TITLE
(Maybe) Picking a New Theme

### ISSUE THREAD

**Issue by pkscout** [xbmc/kodi-tv#84]
I mentioned in the Slack channel that I'm starting to feel like the current PatternFly theme isn't our best choice. I'm building functionality (like blog posts) that other themes have out of the box (at least the beginnings anyway), and "simple" things like dropdown menus and responsive design don't seem fully baked in the Patternfly theme. I'm not saying we have to change, but I would be open to trying something else.  Each comment below is one of the themes I've found that might be worth a look. Feel free to comment or suggest others. If you like one of the themes, give it a thumbs up as a kind of vote.  All three of these cost something, but none of them are more than $30.

**Comment by pkscout** [comment]
Rewy
https://preview.themeforest.net/item/rewy-gatsby-react-it-startup-template/full_screen_preview/28447707

**Comment by pkscout** [comment]
Omega
https://themeforest.net/item/omega-react-next-landing-page-templates/27681215

**Comment by pkscout** [comment]
Appion
https://themeforest.net/item/appion-react-next-landing-page-template/25999268

**Comment by Razzeee** [comment]
Anything that's using tailwindCSS?

**Comment by pkscout** [comment]
None of the ones I picked mentioned that, but let me try searching. If we could use a layout css you're familiar with (even if it means redoing the layouts we already have, that would be a bonus.

**Comment by pkscout** [comment]
OK here are some Tailwind possibilities. It would probably take a little while for me to understand Tailwind enough to replace all the Patternfly layout stuff, but that's not insurmountable. None of these have all the pieces (like blog posts and drop down menus), but I'm guessing if you already know Tailwind those wouldn't be that hard.

Version of Gatsby Serif theme using Tailwind for layout
https://github.com/windedge/gatsby-tailwind-serif

Gatsby Starter with Tailwind and Typescript
https://www.gatsbyjs.com/starters/impulse/gatsby-typescript-tailwind

Gatsby Markdown Typescript Starter
https://stackrole.com/jamstack/gatsby-markdown-typescript-personal-website

**Comment by Razzeee** [comment]
Hrm, might not be that nice?

Maybe removing patternfly and just replacing it with compenents from https://tailwindcomponents.com/components/ or doing our own ones would be an option.

Or just spend some money on this https://tailwindui.com/components but that should boost us and also give us quiet a modern look

**Comment by pkscout** [comment]
Yea, I'm starting to think a fresh start might not be a bad idea.  There are at least a couple things I have to figure out:

1- how to construct a Gatsby Theme (I mean, how hard can it be, header footer, layout).  '-)
2- getting MDX files to be processed as page content without having to load them into GraphQL and then query them back out. The PatternFly theme has this built in, and I think I see how it would be done with the gatsby MDX plugin.

The extent of my layout experience really is header, footer, left column, right column, center. And I think for us left and right columns could just be padding to keep the page width reasonable on big monitors.  I think almost everything else could be done with top menu hierarchy.

I think I'll do a fresh gatsby site install and see what I can figure out.

**Comment by Razzeee** [comment]
On theme authoring https://www.gatsbyjs.com/docs/how-to/plugins-and-themes/building-themes/

Then again, it's not clear to me, if we need to do that or even which benefits it would bring.

**Comment by pkscout** [comment]
I'm starting to have that same question.  Gatsby uses the word theme somewhat differently that I'm used to.  It seems like the benefits to themes is if you want to share them. But they seem to have functionality built into them as well as layout, and I always think about a theme as just the layout. So for us using a starter and then just building off that might be the way to go.

**Comment by pkscout** [comment]
We decided to go with TailwindCSS and build the site layout from scratch. I'm going to close this.
