### ISSUE TITLE
Raspberry Pi Black Screen After Exit

### ISSUE THREAD

**Issue by PipeDeveloper** [xbmc/kodi-tv#86]
As the title.

Im using Raspbian OS, just a fresh and clean .img file form raspberrypi.org

How to reproduce:
From desktop just launch the program and then put exit. The screen goes black, the only way to get working again is unplug the raspberry.

**Comment by pkscout** [comment]
I'm sorry you're having problems with Kodi.  This is the repo for our new web site though, so I'm not really going to be able to help from here.  I'd suggest you visit our forums at https://form.kodi.tv.  If you would really rather submit an issue here, you should go to https://github.com/xbmc/xbmc.  Please note we do ask folks to submit a complete bug report there, which will require more detail than you provided.  Thanks.  I'm going to close this issue.
