### ISSUE TITLE
Make donate button more prominent

### ISSUE THREAD

**Issue by yol** [xbmc/kodi-tv#860]
Ideas:
* add some icon next to it
* different color?
* make it stand out more in some form

**Comment by ProfYaffle** [comment]
So it doesn't get lost in Slack... quick-and-dirty sample re-colouring of donate button on main website - it shares a class with the download button, but otherwise...

![image](https://github.com/xbmc/kodi-tv/assets/6093716/5ccec254-b201-41b7-8e6a-650180401054)

**Comment by ProfYaffle** [comment]
That's _rgb(231 88 23)_, FWIW, but I'm not wedded to it.

**Comment by basrieter** [comment]
I create this as an option:

![image](https://github.com/xbmc/kodi-tv/assets/1310443/13cdd8eb-97fb-4620-a6f7-d41976fd6d02)

It basically makes the forum and the main site have the same buttons for downloads and donations.

**Comment by basrieter** [comment]
Thanks @razzeee. How can we get https://github.com/xbmc/kodi-forum/issues/5 done?
