### ISSUE TITLE
Add webOS download

### ISSUE THREAD

**Issue by yol** [xbmc/kodi-tv#863]
@KarellenX ?

**Comment by KarellenX** [comment]
Is there a webOS logo suitable for use on the download page?

**Comment by ProfYaffle** [comment]
https://en.wikipedia.org/wiki/WebOS#/media/File:LG_WebOS_New.svg or there's one on the wiki page (which may be the same)

**Comment by KarellenX** [comment]
Thanks profyaffle. Found one on google already.
webOS has been added to the download page.

**Comment by yol** [comment]
Thanks @KarellenX!
