### ISSUE TITLE
(Blog) Time Zone Format/Display

### ISSUE THREAD

**Issue by ProfYaffle** [xbmc/kodi-tv#97]
It seems that the blog (at least) subsystem defaults to US mm/dd/yyyy format. Time itself looks local, although I can't tell until we change our clocks in Europe as I'm in GMT for another ten days or so, so they're the same thing.

The preview then shows time in US long format (again, subject to TZ caveat above).

See image, with editor date on left and preview date on right:

![image](https://user-images.githubusercontent.com/6093716/111613095-10d3d000-87d6-11eb-9485-2b6b61376ff9.png)

I'd suggest that, if this isn't configurable on a per-user level to local time/format, the first of these should at least be an unambiguous format so we can immediately see the difference between 5th March and 3rd May. While you can see it in the preview, it's not ideal when it's the editor date that you'd set.

**Comment by pkscout** [comment]
There doesn't seem to be a way to set this per user.  In staging I updated the format to <day> <short month name> <year> with time in 24 hour notation.  I did confirm that it respects your local timezone.  I'll leave this open until things get merged back into main so we can confirm this will work for folks.

**Comment by pkscout** [comment]
I'm wondering if we should change the blog post date format (both card and full post) to use the same DD MMM YYYY format. We don't need to (and shouldn't) use US date style just because that's the one I'm used to.

**Comment by Razzeee** [comment]
While it would be possible to use the `Intl` api https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl I don't think it's a good idea. It would only make sense if our content would also be translated.
